### PR TITLE
44 push notifications

### PR DESCRIPTION
**Pull request by clemens-huebner**

### CODE REVIEW

**Comment by trungluongquang** [comment]
I try to push a notification but I receive no notification. I tested with event Luong and event on 23/06/2016 and the user is u10

I even tried to test with push test in backend but the result is false. Did I miss anything?

**Comment by clemens-huebner** [comment]
@trungluongquang You have to be logged in and joining the event
Please note that if the app is open the push notification is displayed directly as a pop up.

**Comment by clemens-huebner** [comment]
@clemens-huebner And, of course,  you have to enable push notifications in the settings of the app.

**Comment by Najmeddineaskri** [comment]
@clemens-huebner I close this pull request now because it depend on #47.
Please take your time on testing and when you are sure that it work, do your pull request.

**Pull request closed without merging**
