### PR TITLE
86 edit event button for organizer

### PR DESCRIPTION
**Pull request by soniahidri**
The button "pencil" (change event in upper right corner) is not visible and availible to me as an organizer after 48 hours after finishing an event.

### CODE REVIEW

**Comment by soniahidri** [comment]
@trungluongquang the build on travis Ci failed because of the feedback.test.js, I tried to adapt it, but it doesn't work.
@clemens-huebner can you please adapt the feedback test.

thanks in advance.

**Comment by trungluongquang** [comment]
Okay. Let me do it. I know the problem

Am Montag, 11. Juli 2016 schrieb soniahidri :

**Comment by trungluongquang** [comment]
@soniahidri : i cannot pull this branch to my computer to make change. Do you have any ideas, what is the problem here?

**Comment by trungluongquang** [comment]
@soniahidri I move the checking function from controller to service to simplify the making of dump test for you. Furthermore, I may also need the checking admin role function for one of my improvement.

Do you have any complaints? I will wait for you reply before merging

**Comment by trungluongquang** [comment]
@soniahidri I have a question here. Why do we need to check whether a user is an administrator? As I read your User story description, you just need to deal with organizer role, not administrator. Administrator has no special role (in your user story). Did POs change anything here?
@KatharinaGrasser

**Comment by soniahidri** [comment]
@trungluongquang is not mentioned on the description of this u.s, but I think is should be implemented in my case, while If I don't check whether is Admin also Admin can not update previous event and event without date.

I think, it is a mandatory improvement.

**Comment by trungluongquang** [comment]
@soniahidri I appreciate this idea. However, it would be safer for you (and also for me) if you separate improvement and assigned user story into 2 different branches / pull request. Just create a pull request for what you must do and then a different pull request for the improvement.

I will merge the must-do pull request first and wait for POs answer before merging the improvement.

**Comment by soniahidri** [comment]
@trungluongquang ok got it :+1:

**Comment by soniahidri** [comment]
@trungluongquang checking admin function is removed.

**Comment by trungluongquang** [comment]
@soniahidri it looks okay now. However, could you remove the following function because it is a part of checking Administrator role, which we don't implement in this branch but improvement:
1. function isCurrentUserAdmin in services.js
2. the dump test of isCurrentUserAdmin in unit-test

You should implement those function in the branch of improvement, but not here

**Comment by soniahidri** [comment]
@trungluongquang removing is done.

**Pull request merged**
