### PR TITLE
83 ending time

### PR DESCRIPTION
**Pull request by clemens-huebner**

### CODE REVIEW

**Comment by muradIsa** [comment]
@clemens-huebner , why do you simulate successful login in your unit test? It is redundant.

**Comment by muradIsa** [comment]
@clemens-huebner basically you don't need to create so big event mock object. title attribute is enough. and later you should test if backendService.create event function was called with this particular value of the attribute of the event object. The same about alert message, you should check whether alert was called with the right message: "event "mockTitle" created".

**Comment by clemens-huebner** [comment]
@muradIsa Thanks for your review.
I created this "big" mock object on purpose to see if other important fields like date, begin, etc are also transferred right to the backend. When checking an interface it's no bad idea to check not only one little part if it ;)
I used the mockEvent.title attribute in the checking of the popup for maintainability: If you change the mockEvent object now you don't want to look through the whole code for hard coded parts of it.

**Comment by muradIsa** [comment]
@clemens-huebner in this case you can add tens of new attributes to your mock object and your test will still run without error :) If you add {uselessAttribute: "blabla"} to your mock object test will be successful anyways. So your test doesn't mean that implicitly adding all this attributes will ensure that they are transferred right to the backend. By the way, "participants" and "questions" attributes are never passed to the backendService.createEvent function, backendService.createEvent function is never called with object containing this attributes, so in this case they are in the role of "uselessAttribute". As I understand, one test should describe one particular use case. We need to check whether some function was called with right argument list (values) or if we check variable we should test whether some variable has the right value.

**Comment by clemens-huebner** [comment]
@muradIsa You're right, that can be done leaner! Thanks! :wink:

**Pull request merged**
