### PR TITLE
62 notification for organizer

### PR DESCRIPTION
**Pull request by muradIsa**

### CODE REVIEW

**Comment by Najmeddineaskri** [comment]
@muradIsa good job the functionality is done, but your branch is not up to date. I try to resolve the conflict but some functions will have problems of conflict . It will be better if you make your branch up to date in order to be sure that our master stay safe.

thanks for your comprehension.

Best Najm.

**Comment by muradIsa** [comment]
@Najmeddineaskri, before creating a branch I pulled master and created branch based on master. "making branch up to date with master" means merging it with master. It is responsibility of release manager to merge pull requests. And it is quite usual that branches have conflicts with master. It is not the first time that we get conflicts by merging pull requests.

**Comment by Najmeddineaskri** [comment]
@muradIsa it is not not about merging conflict I have resolved the conflict locally, but after that many function doesn't work. 

anyway thanks for your help.

**Comment by muradIsa** [comment]
@Najmeddineaskri There are two possibilities why "many functions" doesn't work after merging this branch:
1) new functions that was added in this branch somehow affect that "many functions" and break them
or
2) branch was not properly merged at all

and be more precise please, what do you mean by "many functions"? Which functions do you mean?

**Pull request merged**
