### PR TITLE
44-47-push-notifications: Fix bug with sendReminder

### PR DESCRIPTION
**Pull request by clemens-huebner**

### CODE REVIEW

**Comment by trungluongquang** [comment]
could you check it again? I tested it but received no push notification (I waited for about 15 minutes)
- user to receive push notification: u10
- user to click on "An Event erinnern": admin / admin
- event: 
- Test organizer - cd7b18f5-6031-4e0a-80b0-8753b6cde25e
- Event novem - 33b0a2da-655c-4ebe-b840-9349abe98f64

Or did I make any mistake while testing this function?

**Comment by trungluongquang** [comment]
besides, I think it would be better if after clicking on this reminder button, there will be notification that "you have successfully sent a notification to all participants"

**Comment by clemens-huebner** [comment]
Please note that push notifications are only available for android devices. Push Notification for iOs requires a membership in the Apple Developer Program.

The notification is a good idea, I can add it.

**Comment by trungluongquang** [comment]
@clemens-huebner yes. I tested on my Android with Phonegap. Yesterday I could receive notification from a function of Murad

**Comment by clemens-huebner** [comment]
The notification goes only to "joined" users, not to "attended" ones (as specified). I think that makes logical sense because when you are "here" you do not need a notification again.
But changing this would be possible.

**Comment by trungluongquang** [comment]
okay. It works now
and do you have a definition of push notification? I always think that push notification is something which appear in the header menu of smartphone. I call what is showing in your function as a pop-up.

Just a minor thing so I still merge this branch

**Comment by trungluongquang** [comment]
and about status "attended" and "joined". In my opinion, just keep it as it is now

**Pull request merged**
