### PR TITLE
78 availability geolocation button

### PR DESCRIPTION
**Pull request by Najmeddineaskri**
The Geo. button is now available between the begin and the end time of the event.
for example : begin 09:15 ; end 18:15.
at 9:16 the button is shown but at 18:16 is not shown.

### CODE REVIEW

**Comment by clemens-huebner** [comment]
@Najmeddineaskri You cannot delete the whole test file just because a test is failing.
If you look at the error message, it is failing in the function written by you, so there might be an error in it.

**Comment by Najmeddineaskri** [comment]
@clemens-huebner my priority now is to finish the assigned task in time, i don't have so much time to adapt the test written by you to my done function. If you make fun with unit test,  you can mybe adapt your Test to the current function.

**Comment by clemens-huebner** [comment]
@Najmeddineaskri It is absolutly no option to delete the work of others just to make personal progress.

**Comment by Najmeddineaskri** [comment]
@clemens-huebner basically the error in your test file, 
you have written it, depend of other Developpers function that mean every update on the EventCtrl we made, we should also made an update in your test file and this is so ugly. please don't make it personally thing and we should focus on our tasks (fixing Bugs, finishing user stories, make improvement, prepare Demo day...)

**Comment by clemens-huebner** [comment]
It is simply unbelievable how less you care about the work of others if you want to make personal progress.
I'm glad I can adapt our test to your user story.

**Comment by clemens-huebner** [comment]
I'm afraid the functionality of your user story is not correct, too. You do not check if the current user joined the event.

**Comment by Najmeddineaskri** [comment]
@clemens-huebner 

Firstly, this is your test not our, i don't understand why you persist to defend your mistake : I still not understand why you integrate the whole EventCtrl in your test case before finishing of our work.

Secondly, The power is to admit when you're wrong.

for me this theme is closed.

**Comment by Najmeddineaskri** [comment]
@clemens-huebner there is no value, to check if the user is joined or not.

**Comment by clemens-huebner** [comment]
@Najmeddineaskri We store the joined users in the backend.

**Comment by Najmeddineaskri** [comment]
@clemens-huebner it's very simple, the Geo. button will be  available between event begin and event endtime independent of user status.

**Comment by clemens-huebner** [comment]
@Najmeddineaskri If you look at the sprint backlog entry you can see that it is about "a user who joined the event".

**Comment by trungluongquang** [comment]
@Najmeddineaskri 
1. There are problem with iPhone.
   Details:
- Testing devices: iPhone 5s
- Build the installation with xCode and also try with phoneGap
- Event: 06e4d712-4074-4259-9a46-7a0a892cd893
- I tried to login with user u10 in both Android and iPhone. Only on Android, I can see the I'm here button
1. As I understand, there is still one missing part in your pull request "In case I push the button without having joined the event, the join button will autmoatically change to join event"

@KatharinaGrasser I think that you POs did not correctly describe this user story. It should be "In case I push the button without having joined the event, the join button will automatically change to _**leave**_ event" <-- it means that when an user, who has not joined the event beforehand, click on "I'm here" and then his attendence is confirmed, his status will be changed to joined

Could you check it again?
1. @clemens-huebner which user story did you find the "a user who joined the event"?

**Comment by clemens-huebner** [comment]
@trungluongquang Obviously the user story was changed today without notification. Find the old version attached.

I thought Jürgen might have an overview before the event who wants to join the event and therefore a joining is necessary. Now, a user can just click "I'm here" without having joined before.

**Comment by trungluongquang** [comment]
@Najmeddineaskri have you already found a solution for the disappearance of "I'm here" button on iPhone?

@clemens-huebner in this case, we have to follow the new description. However, POs should inform us whenever they make changes

**Comment by Najmeddineaskri** [comment]
@trungluongquang I am working on right now, when i resolve the problem i will inform you.

**Comment by Najmeddineaskri** [comment]
@trungluongquang can you please check this pull request again on iphone device.
about visibility of the Button only for joined user, it make no sense,  to implement it now while i have already implemented a function to change the join event button to leave event button if the user has attended the event. you can also verify this function : you need only to change the user status to attended  and showing the event entry screen.

**Comment by trungluongquang** [comment]
@Najmeddineaskri Now I can see the button on both Android and iPhone but it does not work on both of them.

Details:
- Testing devices: iPhone 5s and Xiaomi Note 3
- account: luongadm@gmail.com
- event: Luong Test Event - dbbce48c-5860-4185-915e-cd7315f7e1b7

**Comment by trungluongquang** [comment]
ah no. It works with event test999 - 729d0d16-61dc-43bb-b59a-768b7cf26a32
However, on iPhone, it does not show the map. I know that it is not important so could we remove the map? Only the calculation is enough

The problem of my first test is that some events are without coordinates. In that case, I would like to suggest you to add one minor improvement: when a user click on "I'm here" button of an event, which does not have coordinates, there will be a notification: "Sorry, this event is without specific coordinates so we cannot confirm your attendance"

@KatharinaGrasser how do you think about this improvement? Obviously, if it is so hard, we can let it be like now

**Comment by clemens-huebner** [comment]
@trungluongquang Maybe the ImHereButton should not be visible at all in this case?

**Comment by trungluongquang** [comment]
@clemens-huebner good suggestion. However, since it is an optional improvement, the decision is up to @Najmeddineaskri and POs

**Comment by clemens-huebner** [comment]
@trungluongquang Sure. It does not have to be part of this pull request, we can just add a new branch for the improvement

**Comment by Najmeddineaskri** [comment]
@trungluongquang I think for the description in the sprint backlog, this user story is finish.
If you have a suggestion please don't add it by your self to be part of this u.s but you can write a short email with short explication.
we can make an improvement for the proposed things.

thanks a lot for your comprehension.

**Comment by Najmeddineaskri** [comment]
@trungluongquang about showing the Map on iphone we have a u.s in our sprint backlog #90-Geolocation-Button-For-IOS and I am working on it now.

**Comment by trungluongquang** [comment]
as I mentioned above, the decision to make an improvement or not and how to make this improvement is completely up to you @Najmeddineaskri . Suggestion is only obligation.

This user story is complete as the description and I will merge it later

**Pull request merged**
