### PR TITLE
48 help contact

### PR DESCRIPTION
**Pull request by clemens-huebner**

### CODE REVIEW

**Comment by trungluongquang** [comment]
@clemens-huebner 
1. After clicking on "Mail an Support senden", nothing happens. 
2. Test with iPhone 5s
3. user: luongadm@gmail.com
4. as I read the US description, there is no need to have edit-contact page?

**Comment by clemens-huebner** [comment]
Could you try again, please?

**Comment by trungluongquang** [comment]
- with installation on iPhone, this function works
- with Phonegap on Android, this function does not work

I see the email address is your email address

**Comment by clemens-huebner** [comment]
@trungluongquang That's known. It's the same with mailing participants list. It only works with apk and ios, not with phone gap serve

**Comment by trungluongquang** [comment]
I see. I will merge it later when you change the recipient email

**Comment by clemens-huebner** [comment]
@trungluongquang The mail adress is stored in the backend, you can change it directly in the app 😉

**Comment by trungluongquang** [comment]
@clemens-huebner just test again and it does not work on Android. It works normally on iPhone

**Pull request merged**
