### PR TITLE
47 notifications settings

### PR DESCRIPTION
**Pull request by clemens-huebner**

### CODE REVIEW

**Comment by Najmeddineaskri** [comment]
@clemens-huebner  I made all required steps, but push notifications still not working.
please check it again.

**Comment by clemens-huebner** [comment]
Can you please explain more detailled where you see expected behaviour?
It would be useful if you can say what steps you performed, which user you used, what event you looked at, which step failed, etc.

**Comment by Najmeddineaskri** [comment]
firstly I have checked your branch #47. I have enabled the push notification and I have joined the upcoming event.
secondly I have checked the branch #44 I have logged in with "admin" and I have pushed the button reminder. 
finally I checked the two branches #47 and 44 I have logged in with "najm" and i did not received an push or pop-up notification.

**Comment by Najmeddineaskri** [comment]
@clemens-huebner once I have checked your branch #47, I have logged in with user "najm".

**Comment by Najmeddineaskri** [comment]
@clemens-huebner I think, It will be better when you merge the two branches in one to succeed the test and make it easier for you and for the release manager.

**Comment by clemens-huebner** [comment]
@Najmeddineaskri Very good idea :D
Could be mine :P

**Pull request closed without merging**
