### PR TITLE
59 availibility of feedback

### PR DESCRIPTION
**Pull request by clemens-huebner**
Uses geo location, so merge 38 first, please

### CODE REVIEW

**Comment by trungluongquang** [comment]
could you check it again? I tried with users, whose status is "attended" but I do not see feedback button.

The tested event is ba7a7934-b0bb-42f9-8d56-f856bd28dcaa

**Comment by clemens-huebner** [comment]
Thanks, there was a problem.
I fixed it, should work now. 
For making merging easier for you, I already integrated master.

**Comment by trungluongquang** [comment]
quite strange. I see no feedback button.
test with event: 31497afb-9a6d-45bf-9567-06b55b6432f9

I will leave this user story to next week and focus on other two now

**Comment by clemens-huebner** [comment]
@trungluongquang 31497afb-9a6d-45bf-9567-06b55b6432f9 is a future event (in july) and therefore feedback is not available.
Works as defined. Go on ;)

**Comment by trungluongquang** [comment]
actually, it works but not totally correct. When the event is in the same day, I see feedback button but when it is the next day, we cannot see feedback button
it is not as required "during 48 hours" so I will leave this pull request open. In case this is a mistake by me, I will try to merge it before the meeting

**Pull request merged**
