### PR TITLE
delete event and related agenda, files

### PR DESCRIPTION
**Pull request by trungluongquang**

### CODE REVIEW

**Comment by Najmeddineaskri** [comment]
@trungluongquang Firstly I can not check your pull requests ? 
Secondly, instead of the many pull request you can do It in your branch and once you finished your job do only one pull request for all your work.

**Comment by clemens-huebner** [comment]
@Najmeddineaskri Please provide detailed information about what fails when you cannot test it successfully. Otherwise it is no help for the developer. ;)

**Comment by trungluongquang** [comment]
@Najmeddineaskri I think that there are some misunderstanding in the working process here. As far as I know, for each user story, we need to create a new branch and when we finish our user story, we create pull request for it. We should not create one pull request for all of our weekly task

**Comment by Najmeddineaskri** [comment]
@clemens-huebner can you please tell me to which branch this pull request is assigned ?

**Comment by clemens-huebner** [comment]
I don't really get your question, but as you can see above this pull request is about merging 63-delete-event into master.

**Comment by trungluongquang** [comment]
@Najmeddineaskri  it is 63-Delete-event

you can see it here: http://imgur.com/F1SErHZ

**Comment by Najmeddineaskri** [comment]
@trungluongquang   the misunderstanding is that we are used to rename the pull request with the branch name but I see now you different branches :)

**Comment by trungluongquang** [comment]
@Najmeddineaskri got it. Because we have not officially agreed on pull request name so I do not really pay much attention about this thing. In my next pull requests, I will add branch number or prefix (bugfix, improvement) to make it more understandable

**Pull request merged**
