### PR TITLE
58 remember login

### PR DESCRIPTION
**Pull request by clemens-huebner**

### CODE REVIEW

**Comment by Najmeddineaskri** [comment]
@clemens-huebner the remember me function still not working, please check it again.
if  I checked the remember me checkbox or not, nothing happens

**Comment by clemens-huebner** [comment]
@Najmeddineaskri Again: Please be more detailed.
What user did you use? What steps did you execute? In browser? Phonegap serve? APK? Where did you see unexpected behaviour?

**Comment by Najmeddineaskri** [comment]
@clemens-huebner the acceptance criteria for this user story is : As a user or as an organizer, after ticking the "Remember me" button within the log in screen, I stay logged in, if the remember me function is not choosen I have to insert my username and password every time I want to log in.

whatever the user should this function worked. I used phonegap serve to test this function.
what is unexpected is that after clicking the "Remember me" button and login and Logout. if now I want to login, I should enter my Login information again.

If you mean that this function work only on APK please send me the APK file.

Please in the future a short description about your pull requests will be better.

Best
Najm

**Comment by clemens-huebner** [comment]
@Najmeddineaskri: I'm not sure if you are misunderstanding this user story. It is not about prefilling the login form so the user does not have to enter the credentials again, its about storing the whole session of the user so he does not even have to go to the login form. Of course, if the user logs out actively, his session is not stored any longer.

You can test that like that in three cases (phoengap serve works):
A.
1. Login as a user, e.g. testuser, and tick "Remember me" 
2. Close the app (not only leave it, close it)
3. Open it again.
Expected result: The user is logged in, the menu shows the options of a logged in user, you can see his data in My Account

B. 
1. as above in A
2. Log out
3. Close the app (not only leave it, close it)
4. Open it again
Expected result: The user is not logged in.

C. 
1. Login as a user, e.g. testuser, and NOT tick "Remember me" 
2.-3. as above in A
Expected result: The user is not logged in.

**Pull request merged**
