### PR TITLE
Bugfix participants list for iphone

### PR DESCRIPTION
**Pull request by muradIsa**

### CODE REVIEW

**Comment by Najmeddineaskri** [comment]
@muradIsa  I think that unit test case is mandatory for every change functions, but in this user story i don't see any test.

**Comment by Najmeddineaskri** [comment]
dod

**Comment by muradIsa** [comment]
@Najmeddineaskri, there is no such a user in the Sprint Backlog, and remember what was discussed on Wednesday meeting and yesterday!

**Comment by trungluongquang** [comment]
@muradIsa could you check it again. There may be some problems because now I cannot download or sending participant list by mail

test on both iPhone and Android with Phonegap

**Pull request merged**
