### PR TITLE
68 feedback results after event

### PR DESCRIPTION
**Pull request by clemens-huebner**
This covers US 68 as well as US 70 because the fixed bugs influenced both of them.

### CODE REVIEW

**Comment by Najmeddineaskri** [comment]
@trungluongquang did you tested this u.s on ios. I tested it and it not working.!!!

**Comment by trungluongquang** [comment]
I did test it and it works. The Feedback result button is only shown in events, which have been past
testing by building and install the branch in my iPhone

**Comment by Najmeddineaskri** [comment]
@clemens-huebner hopefully, I tested with phonegap (iphone 5s) before two hours and it doesn't work.

**Comment by clemens-huebner** [comment]
@Najmeddineaskri As mentioned many times before, a "it doesn't work" is not very helpful. Please provide more information (which user? which event? which date? etc.)

**Comment by Najmeddineaskri** [comment]
@trungluongquang  hhhhh play your game and good luck with it :+1:

**Comment by trungluongquang** [comment]
what game?

**Pull request merged**
