### PR TITLE
Bugfix 94 insert new question

### PR DESCRIPTION
**Pull request by clemens-huebner**

### CODE REVIEW

**Comment by trungluongquang** [comment]
could you check it again? I cannot add new questions

**Comment by clemens-huebner** [comment]
@trungluongquang Which Event?

**Comment by trungluongquang** [comment]
I tested it again and find out that the problem may be the cache. Anyway, I will describe the problem:
- event: Luong test chsnge 2
- add question --> successful notificaiton but no changes in the list of question from the second question added
- in backend, new questions are stored

since i cannot run this function properly, I'm not sure about the thing you have made

**Comment by clemens-huebner** [comment]
@trungluongquang Thanks for your description, I will have a look at it again

**Comment by clemens-huebner** [comment]
@trungluongquang The problem is with your event ;)
If you have a look at the document in the backend, you see that you have the complete same question multiple times in your question array. So the ng-repeat fails (what you could see in console). So the problem is with displaying, not with adding (if you look at backend, you find the added questions anyway).
This is not happening with an event with correct question object, e.g. Trung test update event information.

**Comment by trungluongquang** [comment]
unfortunately, it does not work for me. I will show you my problem when we meet today

**Pull request merged**
