### PR TITLE
38 Geolocation-button 

### PR DESCRIPTION
**Pull request by Najmeddineaskri**
Get current position, calculate distance between two position using coordinates (Latitude, Longitude), showing the google map.

### CODE REVIEW

**Comment by trungluongquang** [comment]
@Najmeddineaskri 
- firstly, please be careful with your commit. As I check, the services.js does not work because the redundant + from line 406
- secondly, I do not see any value in adding status "not attended". It is really kind of you trying to improve this function but that change will effect other functions. For example, isCurrentUserRegisteredForEvent. Because right now we have some argument over this change and the deadline is today, please help me by playing safe

**Comment by Najmeddineaskri** [comment]
@trungluongquang for the first thing is already solved. for the second thing, i 'll ask you a short question, can you please tell me what's the difference between the two function who make user attended and not attended. if it's have conflict i hope you can tell me exactly where. 

thanks.

**Comment by trungluongquang** [comment]
1. not developer but business aspect: this improvement makes no significant value here while it causes minor arguments
2. isUserRegisteredForEvent check searchResult[0].status == "joined"
   "not attended" is not that user did not join but if you change status to "not attended", isUserRegisteredForEvent will not work correctly

**Comment by Najmeddineaskri** [comment]
@trungluongquang I did not understand what do you mean and I'm waiting for the answer to my question. can you please more explain i ask for the difference between the two function. if not attended fails and make conflict attended also will be fails.

**Comment by clemens-huebner** [comment]
The problem is not with attendend or not attended.
The problem is - as Luong said - with isUserRegisteredForEvent.

**Comment by Najmeddineaskri** [comment]
@clemens-huebner can you please explain the problem to me ? as i see it make no problem.

**Comment by clemens-huebner** [comment]
Sorry, Najm, I don't have the time to do so now. I have to finish my user stories for tomorrow.
It already took me a lot of time with this "improvement", the same with Luong, I think - and I don't see good will at you accepting explanations, to be honest, so that might took long.
Maybe I can do so later.

**Comment by Najmeddineaskri** [comment]
@clemens-huebner @trungluongquang I would like before give me answer. please check my code if it makes conflict. I remove it right now.

**Comment by trungluongquang** [comment]
@Najmeddineaskri as I mentioned above, the most important thing here is not from developer aspect but business: what good does it make?. Frankly, I'm not so sure about the consequence of changing status "attended", "not attended" and "joined" but since it has the possibility to affect other, I would like to play safe.

Furthermore, please discuss before making changes. What we must do is follow the sprint backlog and for anything else, it falls into (1) improvement, (2) bugfix, (3) new user story. For any of these 3, you should create a new branch. By doing so, even if we still cannot agree on this issue, we still have what we must do for this week.

Last but not the least, we can save a lot of time and focus on more urgent issue by playing safe with this function. Leave discussion till tomorrow or next SDs meeting.

**Comment by Najmeddineaskri** [comment]
@trungluongquang thanks for your reply. I'm pretty sure that it have no impact to other work and other function. I tested my code many time and I have the agree of the PO. please don't make it personal thing. if you don't want to merge it  I can understand you.
merci

**Comment by trungluongquang** [comment]
@Najmeddineaskri no problem at all. I just want to play safe now because deadline is tomorrow. Furthermore, my top priority now is to deliver the needed functions for this week or newly proposed issues.

You should create a pull request for this improvement and we will decide whether it should be accepted tomorrow or after our meeting tomorrow.

**Comment by Najmeddineaskri** [comment]
@trungluongquang do you have any other questions relating to my current pull request ?

**Comment by trungluongquang** [comment]
@Najmeddineaskri I checked and it worked however I do not think that it is perfect. However, I will merge it now because the function is okay but in the following, you can see something which should be improved next week:
1. The logic of function: I'm not so sure that whether user is allowed to click "Ich bin hier" button when they have not registered for the event. I will ask POs tomorrow about this point
2. when you have no GPS, there will a notification that you "nicht besucht". The notification itself is nice but I think the content should be somehow different. For example, please turn on your GPS or check your GPS again. The current notification may cause misunderstanding
3. the position of "ich bin hier" button. When you click on the "Neuen Talk hinzufügen" (remeber to login with administrator role to see this button), the "ich bin hier" button will place in a very ugly place

anyway, your function itself is okay

**Pull request merged**
